name: 'polymer_mvc_codelab'
version: 0.0.1
description: Polymer 1.0 MVC codelab
author: Gonzalo Pezzi <gonzalopezzi@gmail.com>
homepage: https://github.com/gonzalopezzi

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  http: ^0.11.3+3
  polymer_elements: ^1.0.0-rc.8
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.0
  autonotify_observe: ^1.0.0+7
  dson: ^0.3.1

transformers:
- autonotify_observe:
    entry_points: web/index.html
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
